blog/urls.py
# from blog.views import Views
from blog import views
from hypergalaxy import views as Hyper_views
from django.urls import path

urlpatterns = [
    path('blog',  views.PostList.as_view(), name='blog'),
    path('blog/<slug:slug>',  views.DetailView.as_view()),
    # path('blog', Views.index, name='blog')
]

handler404 = Hyper_views.page_not_found

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hypergalaxy.urls')),
    path('', include('blog.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hypergalaxy/urls.py
from hypergalaxy import views
from django.urls import path

urlpatterns = [
    path('', views.index , name='index'),
    path('contato', views.contato, name='contato'),
    path('sendmail', views.send_email, name='sendemail'),
    path('sobre', views.sobre, name='sobre'),
    path('projetos', views.projetos, name='projetos'),
    path('equipe', views.equipe, name='equipe'),
    path('projeto/', views.projeto_padrao, name='projeto-padrao'),

    path('equipe/<int:colaborador_id>', views.colaborador),
    path('projetos/<int:projeto_id>', views.projeto),
]

handler404 = views.page_not_found

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field


class Post(models.Model):

    CATEGORIA = [
        ('N', 'Notícias'),
        ('S', 'Social Mídia'),
        ('P', 'Programação')
    ]

    capa = models.ImageField(blank=False)
    titulo = models.CharField(max_length=68, null=False, blank=False)
    sumario = models.TextField(max_length=120)
    categorias = models.CharField(max_length=1, choices=CATEGORIA, default='N')
    slug = models.CharField(max_length=120, null=False, blank=False)
    conteudo = CKEditor5Field(config_name='extends')
    publicado = models.BooleanField(default=True)
    destaque = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.titulo
    

hypergalaxy/models.py
from django.db import models

# Create your models here.
class Projeto(models.Model):

    CATEGORIAS = [
        ('W', 'Web Design'),
        ('B', 'Branding'),
        ('D', 'Desenvolvimento'),
        ('M', 'Marketing')
    ]

    titulo = models.CharField(max_length=68, null=False)
    capa = models.ImageField(null=False, blank=False)
    descricao = models.TextField()
    categoria = models.CharField(max_length=1, choices=CATEGORIAS, default='W')
    publicado = models.BooleanField(default=True)

    def __str__(self):
        return self.titulo    

class ImagesProject(models.Model):
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)
    imagem = models.ImageField()
    descricao = models.CharField(max_length=55)



class Funcionario(models.Model):
    imagem = models.ImageField(blank=False)
    nome = models.CharField(max_length=100, null=False, blank=False)
    cargo = models.CharField(max_length=100, null=False, blank=False)
    descricao = models.TextField(max_length=255)
    instagram = models.CharField(max_length=168)
    facebook = models.CharField(max_length=168)
    linkedin = models.CharField(max_length=168)

    def __str__(self) -> str:
        return self.nome

hypergalaxy/forms.py
from django import forms

class FormContato(forms.Form):
    nome = forms.CharField(max_length=120, widget=forms.TextInput(attrs={
        'class':'input w-input',
        'placeholder':'Ex. David',
        'id':'Nome'
    }))

    servico = forms.CharField(max_length=255, widget=forms.TextInput(attrs={
        "style":"display:none;",
        "id":"servicos"
    }))

    email = forms.EmailField(max_length=120, widget=forms.EmailInput(attrs={
        'class':'input w-input',
        'placeholder':'Ex. David@gmail.com',
        'id':'email'
    }))

    assunto = forms.CharField(max_length=120, widget=forms.Textarea(attrs={
        'class':'input w-input',
        'placeholder':'Ex. Conte-nos mais sobre sua ideia',
        'id':'Message'
    }))

blog/views.py
from typing import Any
from django.shortcuts import render
from blog.models import Post
from django.views import generic


class PostList(generic.ListView):
    queryset = Post.objects.filter(publicado=True, destaque=False).order_by('created_at')
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagina'] = 'Blog'
        context['post_destaque'] = Post.objects.filter(publicado=True, destaque=True).first()
        return context

class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail_post.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['outros_posts'] = Post.objects.filter(publicado=True, destaque=False)[:2]
        context['pagina'] = 'Blog'
        return context

hypergalaxy/views.py
from django.shortcuts import render, redirect
from hypergalaxy.models import Projeto, Funcionario, ImagesProject
from blog.models import Post
from hypergalaxy.forms import FormContato
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.conf import settings
# Create your views here.


def index(request):
    projetos = Projeto.objects.order_by('titulo').filter(publicado=True)
    funcionarios = Funcionario.objects.order_by('nome')
    posts = Post.objects.filter(publicado=True, destaque=False).order_by('created_at')[:2]
    return render(request, 'index.html', {
        'projetos':projetos, 
        'funcionarios': funcionarios,
        'posts': posts,
        'pagina': 'Home'
    })
    
def projeto_padrao(request):
    return render(request, 'projeto-padrao.html', {'pagina': 'Projeto Padrão'})

def contato(request):
    form = FormContato()
    return render(request, 'contato.html', {
        'pagina':'Contato',
        'form':form
    })

    
def send_email(request):
    if request.method == 'POST':
        form = FormContato(request.POST)
        if form.is_valid():
            nome = form.data['nome']
            email = form.data['email']
            assunto = form.data['assunto']
            servicos = form.data['servico']
            context = {'nome': nome, 'email': email, 'servicos': servicos,'assunto': assunto}
            html_content = render_to_string('email_templates/sendmail.html', context)
            text_content = strip_tags(html_content)

            email = EmailMultiAlternatives(
                subject=f'Cliente | {nome}',
                body=text_content,
                from_email=settings.EMAIL_HOST_USER,
                to=[settings.DEFAULT_FROM_EMAIL]
            )

            email.attach_alternative(html_content, 'text/html') 
            email.send()
            
            messages.success(request, 'Obrigado😊! Mensagem enviada com sucesso!')
            return redirect('contato')
        else:
            messages.error(request, 'Opss 😢, não foi possivel enviar a mensagem!')
            return redirect('contato')
    
    

def sobre(request):
    return render(request, 'sobre.html', {
        'pagina': 'sobre'
    })
    
def projetos(request):
    projetos = Projeto.objects.all()
    return render(request, 'projetos.html', {
        'projetos':projetos,
        'pagina': 'Projetos'
    })
    
def projeto(request, projeto_id:int):
    projeto = Projeto.objects.get(pk=projeto_id)
    images = ImagesProject.objects.filter(projeto_id=projeto_id)
    return render(request, 'detalhes_cases.html', {
        'projeto':projeto,
        'images':images,
        'pagina': projeto.titulo
    })
    
def equipe(request):
    funcionarios = Funcionario.objects.all()
    return render(request, 'equipe.html', {
        'funcionarios':funcionarios,
        'pagina': 'Equipe Hyper'
    })
    
def colaborador(request, colaborador_id:int):
    funcionario = Funcionario.objects.get(pk=colaborador_id)
    return render(request, 'detalhe_colaborador.html', {
        'funcionario':funcionario,
        'pagina': funcionario.nome
    })
    
def page_not_found(request, exception):
    return render(request, '404.html', {
        'pagina': '404 not found'
    }, status=404)

templates/blog/detail_post.html
{% extends 'partials/_base.html' %}
{% block content %}
<div class="section-blog-details">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-medium is-blog-details">
                <div class="blog-details-component">
                    <div class="blog-details-top-content-wrapper">
                        <div class="blog-details-top-content">
                            <h2 class="heading-style-h2">{{ post.titulo }}</h2>
                            <p class="text-size-regular">{{ post.sumario }}</p>
                        </div>
                        <div class="padding-bottom padding-small"></div>
                        <img alt="{{post.titulo}}" width="100%" height="100%" loading="lazy" src="{{post.capa.url}}" class="blog-details-image">
                        <div class="padding-bottom padding-small"></div>
                        <div class="blog-details-bottom-content">
                            <div class="blog-category">
                                <div>
                                    <p>{{ post.get_categorias_display }}</p>
                                </div>
                            </div>
                            <div class="blog-read-time">
                                <div>
                                    Ler 5 min
                                </div>
                            </div>
                            <div class="blog-date-time">
                                <div>
                                    {{ post.created_at | date:"d/m/Y" }}
                                </div>
                            </div>
                        </div>
                        <div class="padding-bottom padding-small"></div>
                        <div class="divider"></div>
                        <div class="padding-bottom padding-large"></div>
                        <div class="blog-details-wrapper">
                            <div class="blog-details w-richtext">
                                {{ object.conteudo | safe }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-blog">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-large">
                <div class="blog-component">
                    <div class="blog-content">
                        <h2 class="heading-style-h2">Aprendizados e insights</h2>
                    </div>
                    <div class="padding-bottom padding-large"></div>
                    <div class="blog-collection-list-wrapper w-dyn-list">
                        {% if outros_posts %}
                        <div role="list" class="blog-collection-list w-dyn-items">
                            {% for post in outros_posts %}
                            <div role="listitem" class="blog-collection-list-item w-dyn-item">
                                <a id="w-node-_1056a08e-031b-e72c-2f9f-fd119f442700-dd75a4f0" href="#"
                                    class="blog-card w-inline-block">
                                    <div class="blog-image-wrapper">
                                        <img alt="{{ post.titulo }}" loading="lazy" src="{{ post.capa.url }}"
                                            class="blog-image">
                                    </div>
                                    <div class="blog-card-content-wrapper">
                                        <div class="blog-card-top-content">
                                            <div class="blog-category">
                                                <div>
                                                    <p>
                                                        {{ post.get_categorias_display }}
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="blog-read-time">
                                                <div>
                                                    <p>
                                                        Ler 5 min
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                        <h5 class="heading-style-h5">
                                            {{ post.titulo }}
                                        </h5>
                                    </div>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="w-dyn-empty">
                            <div>Nenhum item encontrado.</div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="padding-bottom padding-large"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/index.html
{% extends 'partials/_base.html' %}
{% load static %}
{% block content %}
<div class="section-blog-feature">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-medium top-padding-large">
                <div class="blog-feature-component">
                    <div class="blog-feature-top-content">
                        <h2 class="heading-style-h2">Blog e recursos</h2>
                    </div>
                    <div class="padding-bottom padding-large"></div>
                    <div class="w-dyn-list">
                        {% if post_destaque %}
                        <div role="list" class="w-dyn-items">
                            <div role="listitem" class="w-dyn-item">
                                <a href="{% url 'blog' %}/{{ post_destaque.slug }}" class="blog-link w-inline-block">
                                    <div class="blog-feature-image-wrapper">
                                        <img alt="{{post_destaque.titulo}}" loading="lazy" src="{{ post_destaque.capa.url }}" class="blog-feature-image">
                                    </div>
                                    <div class="padding-bottom padding-xsmall"></div>
                                    <div class="blog-feature-top-details">
                                        <div class="blog-category">
                                            <div>
                                                <p>{{ post_destaque.get_categorias_display }}</p>
                                            </div>
                                        </div>
                                        <div class="blog-read-time">
                                            <div>
                                                <p>Ler 5 min</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="padding-bottom padding-small"></div>
                                    <h4 class="heading-style-h4">{{ post_destaque.titulo }}</h4>
                                </a>
                            </div>
                        </div>
                        {% else %}
                        <div class="w-dyn-empty">
                            <div>No items found.</div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-blog">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-medium bottom-padding-large">
                <div class="blog-component">
                    <div class="blog-content">
                        <h2 data-w-id="9fef2b7c-f21f-14c4-110e-45796041c95f" class="heading-style-h2">
                            Blog Hyper</h2>
                        <div data-w-id="e74be52c-bd05-4afc-62f7-0c39600a63ea"
                            class="blog-category-collection-list-wrapper w-dyn-list">
                            <div role="list" class="blog-category-collection-list w-dyn-items">
                                <div role="listitem" class="blog-category-collection-list-item w-dyn-item">
                                    <a href="{% url 'blog' %}" aria-current="page"
                                        class="blog-category-link w-inline-block w--current">
                                        <div>Todos</div>
                                    </a>
                                    <a href="#" class="blog-category-link w-inline-block">
                                        <div>Notícias</div>
                                    </a>
                                    <a href="#" class="blog-category-link w-inline-block">
                                        <div>Social Mídia</div>
                                    </a>
                                    <a href="#" class="blog-category-link w-inline-block">
                                        <div>Desenvolvimento</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="padding-bottom padding-large"></div>
                    <div data-w-id="9fef2b7c-f21f-14c4-110e-45796041c962"
                        class="blog-collection-list-wrapper w-dyn-list">
                        {% if object_list %}
                        <div role="list" class="blog-collection-list w-dyn-items">
                            {% for post in object_list %}
                            <div role="listitem" class="blog-collection-list-item w-dyn-item">
                                <a id="w-node-_9fef2b7c-f21f-14c4-110e-45796041c965-dd75a4f4" href="{% url 'blog' %}/{{  post.slug }}" class="blog-card w-inline-block">
                                    <div class="blog-image-wrapper">
                                        <img alt="{{ post.titulo }}" loading="lazy" src="{{ post.capa.url }}" class="blog-image">
                                    </div>
                                    <div class="blog-card-content-wrapper">
                                        <div class="blog-card-top-content">
                                            <div class="blog-category">
                                                <div>
                                                    <p>{{ post.get_categorias_display }}</p>
                                                </div>
                                            </div>
                                            <div class="blog-read-time">
                                                <div>
                                                    Ler 5 min
                                                </div>
                                            </div>
                                        </div>
                                        <h5 class="heading-style-h5">
                                            {{ post.titulo }}
                                        </h5>
                                    </div>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                        {% else %}
                        <div class="w-dyn-empty">
                            <div>No items found.</div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'components/_cta.html' %}
</div>
{% endblock %}

templates/components/_projetos.html
{% load static %}
<div class="section-project">
    <div data-w-id="1c92dadd-24fe-f382-3ea0-382ef193824b" class="project-tracker">
        <div class="project-component in-home">
            <div class="project-content-wrapper in-home">
                <div class="project-left-content in-home">
                    <div class="project-heading-wrapper">
                        <h2 class="heading-style-h2 is-project">Nossos projetos</h2>
                    </div>
                    <div class="is-background-white"></div>
                </div>
                <div class="project-right-content in-home">
                    {% for projeto in projetos %}
                    <div data-w-id="6aaffbe1-601f-2f86-7b11-efefc3d87c8f"
                        class="project-collection-list-wrapper w-dyn-list">
                        <div role="list" class="project-collection-list w-dyn-items">
                            <div role="listitem" class="project-collection-item w-dyn-item">
                                <div style="background-color:rgb(254,243,240)" class="project-item _4th">
                                    <a href="{% url 'projetos' %}/{{ projeto.id }}" class="project-link w-inline-block">
                                        <h2 class="heading-style-h2">{{ projeto.titulo }}</h2>
                                        <div class="padding-bottom padding-small"></div>
                                        <div class="project-image-wrapper">
                                            <img alt="{{ projeto.titulo }}" loading="lazy" src="{{ projeto.capa.url }}"
                                                class="project-image">
                                            <div class="project-button">
                                                <div>Ver <br>Projeto</div>
                                            </div>
                                        </div>
                                        <div class="padding-bottom padding-xsmall"></div>
                                        <div class="project-category">
                                            <div>
                                                <p>
                                                    {{ projeto.get_categoria_display }}
                                                </p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="w-dyn-empty">
                            <div>No items found.</div>
                        </div>
                    </div>
                    {% endfor %}
                    <div data-w-id="6aaffbe1-601f-2f86-7b11-efefc3d87c8f"
                        class="project-collection-list-wrapper w-dyn-list">
                        <div role="list" class="project-collection-list w-dyn-items">
                            <div role="listitem" class="project-collection-item w-dyn-item">
                                <div style="background-color:rgb(254,243,240)" class="project-item _4th">
                                    <a href="{% url 'projeto-padrao' %}" class="project-link w-inline-block">
                                        <h2 class="heading-style-h2">
                                            Projeto padrão
                                        </h2>
                                        <div class="padding-bottom padding-small"></div>
                                        <div class="project-image-wrapper">
                                            <img alt="Projeto padrão" loading="lazy" src="{% static 'images/projetos03.png' %}"
                                                class="project-image">
                                            <div class="project-button">
                                                <div>Ver <br>Projeto</div>
                                            </div>
                                        </div>
                                        <div class="padding-bottom padding-xsmall"></div>
                                        <div class="project-category">
                                            <div>
                                                <p>UX/UI Design</p>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="w-dyn-empty">
                            <div>No items found.</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/detalhes_cases.html
{% extends 'partials/_base.html' %}
{% load static %}
{% block content %}
<div class="section-project-details">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-medium top-padding-large">
                <div class="project-details-component">
                    <h1 class="heading-style-h1">
                        {{ projeto.titulo }}
                    </h1>
                    <div class="padding-bottom padding-xxlarge"></div>
                    <div class="divider"></div>
                    <div class="padding-bottom padding-medium"></div>
                    <div class="project-content-wrapper">
                        <div id="w-node-_8c24c4bd-5df6-bd3b-e5d9-d7dda8ff8e27-dd75a4f8" class="project-left-content">
                            <h6 class="heading-style-h6">Sumário - Projeto</h6>
                            <p class="text-size-regular">
                                {{projeto.descricao}}
                            </p>
                        </div>
                        <div id="w-node-_8c24c4bd-5df6-bd3b-e5d9-d7dda8ff8e2c-dd75a4f8" class="project-content">
                            <h6 class="heading-style-h6">Cliente</h6>
                            <div bind="54094b6b-02e5-5bc6-3461-5d0f9493b133" class="text-size-regular">
                                <!-- {{ projeto.cliente }} -->
                            </div>
                        </div>
                        <div id="w-node-_8c24c4bd-5df6-bd3b-e5d9-d7dda8ff8e31-dd75a4f8" class="project-right-content">
                            <h6 class="heading-style-h6">Serviço</h6>
                            <div class="service-list">
                                <div class="service-list-item">
                                    <div bind="cd78c6f8-0635-5333-0822-47bf9bab1e16">
                                        {{ projeto.get_categoria_display }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="project-details-background-image"></div>
<div class="section-project-overview-details">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-large">
                <div class="project-overview-component">
                    <div class="project-overview-details w-dyn-bind-empty w-richtext"></div>
                    <div class="padding-bottom padding-large"></div>
                    <div class="w-layout-grid project-overview-grid">
                        <img alt="" loading="lazy"
                            id="w-node-d1b5f31d-0c68-a496-202a-36468abf6061-dd75a4f8" src="">
                            <img alt="" loading="lazy"
                            id="w-node-f493f500-b43c-bf74-ca06-f9fc0feacd1c-dd75a4f8" src="">
                        </div>
                    <div class="padding-bottom padding-large"></div>
                    <h5 class="heading-style-h5">Desafio & Solução</h5>
                    <div class="padding-bottom padding-xsmall"></div>
                    <div class="divider"></div>
                    <div class="padding-bottom padding-large"></div>
                    <div class="project-details-wrapper">
                        <div class="project-details w-dyn-bind-empty w-richtext"></div>
                    </div>
                    <div class="padding-bottom padding-large"></div>
                    <!-- <div class="w-layout-grid project-grid">
                        <img alt="" loading="lazy" width="1195"
                            id="w-node-_530f3fa2-dcdb-c895-3304-d2ab979aabf9-dd75a4f8" src="">
                            <img alt="" loading="lazy" id="w-node-_17232e0f-9def-c1e2-2681-717427f2cfac-dd75a4f8" src="">
                        <img alt="" loading="lazy" id="w-node-_4d3542eb-0e48-a355-816d-1cd37886225a-dd75a4f8" src="">
                        <img alt="" loading="lazy" id="w-node-_0cdd4b06-6607-c94b-f36a-f2035448d98e-dd75a4f8" src="">
                        <img alt="" loading="lazy" id="w-node-_2ccf2b15-548b-4554-7362-8b71fb87554b-dd75a4f8" src="">
                    </div> -->
                    <div class="w-layout-grid project-grid">
                        {% for imagem in images %}
                        <img alt="{{ imagem.descricao }}" loading="lazy" id="w-node-_17232e0f-9def-c1e2-2681-717427f2cfac-dd75a4f8" src="{{ imagem.imagem.url }}">
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-cta">
    <div class="padding-global">
        <div class="container-large">
            <div class="padding-section-xlarge">
                <div class="cta-component">
                    <h1 class="heading-style-h2 text-color-white">Tem uma ideia?</h1>
                    <div class="padding-bottom padding-large"></div>
                    <div data-w-id="4fb7d052-c644-1be1-4548-88d40ee229d4" class="cta-content"><img
                            src="{% static 'images/Arrow.png' %}" loading="lazy"
                            alt="flecha para esquerda apontando para contatos" class="cta-arrow">
                        <div class="cta-button-wrapper">
                            <a href="{% url 'contato' %}" class="cta-button">Conte-nos sobre isso?</a>
                            <div class="cta-heading-line"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/email_templates/sendmail.html
<h1>
    {{ nome }}
</h1>
<hr>
<p>
    <strong>Email:</strong> {{ email }} <br>
    <strong>Serviços:</strong>  {{ servicos }} <br>
    <strong>Assunto:</strong>{{ assunto }}
</p>